import { appSchema, tableSchema } from '@nozbe/watermelondb'

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'trips',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'team_id', type: 'string' },
        { name: 'vehicle_id', type: 'string' },
        { name: 'driver_id', type: 'string' },
        { name: 'origin', type: 'string' },
        { name: 'destination', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'synced', type: 'boolean' },
        { name: 'trip_date', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'trip_events',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'trip_id', type: 'string' },
        { name: 'trip_server_id', type: 'string', isOptional: true },
        { name: 'event_type', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'photo_url', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'is_force_majeure', type: 'boolean' },
        { name: 'fm_type', type: 'string', isOptional: true },
        { name: 'fm_photos', type: 'string', isOptional: true },
        { name: 'diagnostico', type: 'string', isOptional: true },
        { name: 'km_entrada', type: 'number', isOptional: true },
        { name: 'km_salida', type: 'number', isOptional: true },
        { name: 'trabajos_realizados', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'recorded_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'expenses',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'trip_id', type: 'string', isOptional: true },
        { name: 'trip_server_id', type: 'string', isOptional: true },
        { name: 'concept', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'node_code', type: 'string', isOptional: true },
        { name: 'vehicle_plate', type: 'string', isOptional: true },
        { name: 'amount', type: 'number' },
        { name: 'voucher_type', type: 'string', isOptional: true },
        { name: 'voucher_number', type: 'string', isOptional: true },
        { name: 'photo_url', type: 'string', isOptional: true },
        { name: 'photo_local_path', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'synced', type: 'boolean' },
        { name: 'transaction_date', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
})
